-- MySQL Script generated by MySQL Workbench
-- Sat Jun 15 13:13:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Session` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ipExternalCamera` VARCHAR(45) NOT NULL,
  `portIpCamera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ChickesHouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ChickesHouse` (
  `idChickesHouse` INT NOT NULL,
  `latitude` FLOAT(8) NULL,
  `longitude` FLOAT(8) NULL,
  `doorState` VARCHAR(10) NULL,
  `Session_idUser` INT NULL,
  `Settings_id` INT NOT NULL,
  PRIMARY KEY (`idChickesHouse`),
  INDEX `fk_ChickesHouse_Session_idx` (`Session_idUser` ASC),
  INDEX `fk_ChickesHouse_Settings1_idx` (`Settings_id` ASC),
  CONSTRAINT `fk_ChickesHouse_Session`
    FOREIGN KEY (`Session_idUser`)
    REFERENCES `mydb`.`Session` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChickesHouse_Settings1`
    FOREIGN KEY (`Settings_id`)
    REFERENCES `mydb`.`Settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DaySunriseSunset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DaySunriseSunset` (
  `date` DATE NOT NULL,
  `sunrise` TIME NOT NULL,
  `sunset` TIME NOT NULL,
  `ChickesHouse_idChickesHouse` INT NOT NULL,
  PRIMARY KEY (`date`),
  INDEX `fk_DaySunriseSunset_ChickesHouse1_idx` (`ChickesHouse_idChickesHouse` ASC),
  CONSTRAINT `fk_DaySunriseSunset_ChickesHouse1`
    FOREIGN KEY (`ChickesHouse_idChickesHouse`)
    REFERENCES `mydb`.`ChickesHouse` (`idChickesHouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
